export const routes = {
    splash_screen: "splash_screen",
    login_screen: "login_screen",
    registre_screen: "registre_screen",
    forgot_password_screen: "forgot_password_screen",
    otp_screen: "otp_screen",
    interest_screen: "interest_screen",
        home_screen: "home_screen",
    home_main_screen: "home_main_screen",
    search_screen: "search_screen",
    dashboard_screen: "dashboard_screen",
    reset_password_screen: "reset_password_screen",
    game_landing_screen: "game_landing_screen",
    course_landing_screen: "course_landing_screen",
    setting_screen: 'setting_screen',
    drawer_screen: 'drawer_screen',
    profile_screen: 'profile_screen',
    play_game_screen: 'play_game_screen',
    course_detail_screen: 'course_detail_screen',
    class_summary_screen: 'class_summary_screen',
    home_work_details_screen: 'home_work_details_screen',
    enrolled_screen: 'Enrolled',
    graded_screen: 'Graded',
    returened_screen: 'Returned',
    another_user_profile: 'another_user_profile',
    pdf_view_screen: 'pdf_view_screen',
    task_view_screen: 'task_view_screen',
    files_screen: 'Files',
    add_on_Inst_screen: 'Add on Inst',
    game_dashboard_screen: "Game Dashboard",
    leader_boared_screen: "leader_boared_screen",
    class_screen: "Class",
    school_screen: 'School',
    homwwork_summary_sreen: "Home Work Summary Screen",
    draft_Screen: "Draft",
    turned_in_screen: "Turned In",
    student_home_work_screen: "student_home_work_screen",
    evaluatedScreen: "Evaluated",
    studentViweHomeWorkDetailScreen: "studentViweHomeWorkDetailScreen",
    securityScreen: "securityScreen",
    paymentScreen: "paymentScreen",

    changepasswordScreen: "changepasswordScreen",
    cmsScreen: "cms_screen",
    complete:'Completed',
    missed:'Missed',
    helpAndSupportScreen: "helpAndSupportScreen",
    quizSummaryScreen: "quizSummaryScreen",
    quizInstructionyScreen: "quizInstructionyScreen",
    quiz_screen: 'quiz_screen',
    quiz_result_screen: 'quiz_result_screen',
    courseSummaryPage: 'CourseSummaryPage',
    courseDetailScreen: "CourseDetailScreen",
    all_file_screen: "all_file_screen",
    image_view_screen: "Image",
    videoPlayerScreen: "VideoPlayerScreen",
    pdf_editer:'pdf_editer',
    pending: "Pending",
    student_task_detail_screen: "student_task_detail_screen",
    //new routes
    gameinterest_screen:"gameinterest_screen",
    doc_screen:"doc_screen",
    text_screen:"text_screen"
}