

export const strings = {
    googleApiKey: '311736070044-8j39qduc4r4j8v5l2h8jo7dl9t55pcqr.apps.googleusercontent.com',
    appName: "BanyanPro",
    your_learning_companion: "Your Learning Companion",
    powered_by_banyanpro: "Powered by Maantt",
    hey_login_now: "Hey, \nLogin Now.",
    new_user: "New user, ",
    register_now: 'Register now',
    user_id: 'User ID',
    upgrade: "Upgrade",
    password: 'New Password',
    loginpassword: ' Password',
    old_password: 'Old Password',

    please_enter_password: 'Please enter password',
    please_enter_old_password: 'Please enter old password',

    please_enter_user_id: 'Please enter user id',
    forgot_password: "Forgot Password",
    login: "Login",
    login_with_email: "Sign in with Gmail",
    login_with_apple: "Sign in with Apple",

    register_an_account: "Register an account",
    first_name: "First name",
    last_name: "Last name",
    user_id_and_email_address: "User ID / Email",
    mobile_number: "Mobile number",
    mobile_number_email: "Email / Mobile number",

    confirm_password: "Confirm Password",
    sign_up: "Sign up",
    already_have_an_account: "Already have an account? ",
    sign_in: "Sign in",
    please_enter_first_name: 'Please enter first name',
    please_enter_last_name: 'Please enter last name',
    please_enter_user_ya_email_id: 'Please enter user id or email',
    please_enter_mobile_number: 'Please enter mobile number',
    please_enter_email_mobile_number: 'Please enter email/mobile number',

    please_type_a_Comment: 'Please type a comment',
    please_type_a_score: 'Please tyep a score',
    please_type_a_title: 'Please tyep a title',
    please_enter_old_passworda: 'Please enter old password',

    please_enter_confirm_password: 'Please enter Confirm password',
    please_enter_valid_mobile_number: 'Please enter valid mobile number',
    password_reset: "Password Reset",
    enter_your_register_mobile_number: "Enter your registered mobile number",
    enter_your_register_user_id_ya_email: "Enter your registered User ID/Email",

    send: "Send",
    i_am_interested_in: "I am interested in",
    submit: "Submit",
    verify_otp: "Verify Code",
    reset_password: "Reset Password",
    reset: "Reset",
    otp_message: "Enter the 6-digit code sent to your email ",
    didnt_receive_otp: "Didn't receive code?",
    resend_now: " Resend Code",
    please_enter_otp: "Please enter code",
    password_regex: "/^(?=.*\d)(?=.*[a-zA-Z])[a-zA-Z0-9]{7,}$/",
    password_should_be_at_least_8_characher: "Your password must be at least 8 characters",
    explore_to_learn: "Explore to learn",
    lets_play: "Let's Play",
    side_arrow: ">",
    your_password_must_contain_at_least_one_letter: "Your password must contain at least one letter.",
    your_password_must_contain_at_least_one_digit: 'Your password must contain at least one digit.',
    your_password_must_contain_at_least_a_special_cha: 'Your password must contain at least special char from -[ ! @ # $ % ^ & * _ ]',
    password_and_confirm_password_does_not_matched: 'New Password & Confirm Password is not matched',
    settings: "Settings",
    profile: "Profile",
    game: "Game",
    security: 'Security',
    about_us: 'About us',
    is_not_alavailable: ' is not available',
    support_us: 'Help & Support',
    search: 'Search',
    homework: 'Homework',
    teacherComments:'Activity logs',
    studentSubmission:'Student Submissions',

    add_comment: 'Add Comment',
    type_a_comment: 'Type a comment',
    score: 'Score',
    type_a_score: 'Type a score',
    comments: 'Comments',
    lorym_ipsum: 'Lorem ipsum dolor sit amet. Ut consequatur laborum hic quidem consectetur At consequatur vitae. Aut provident quia sed quibusdam tempore et deserunt odit.',
    gameDashboard: "Game Dashboard",
    claim: "CLAIM",
    statics: "Statistics",
    friends: "Friends",
    mySub: "My Subscription",
    basic_plan: "Basic Plan",
    update: "Update",
    turnin:'Turn In',
    photo: "Photos",
    video: "Videos",
    select_image_videos: "Select Photos/Videos",
    select_image_Gallery: "Select Photos/Gallery",
    files: " Uploaded Files",
    delete: 'Delete',
    are_you_sure_you_want_to_delete_the_item: 'Are you sure you want to delete the file?',
    are_you_sure_you_want_to_logout: 'Are you sure you want to logout?',
    are_you_sure_you_want_to_delete_acccount: 'Are you sure you want to delete account?',
    are_you_sure_you_want_to_quit_the_quiz: 'Are you sure you want to quit the Quiz?',
    are_you_sure_you_want_to_submit_the_quiz: 'Are you sure you want to submit the Quiz?',
    are_you_sure_you_want_to_go_back: 'Do you want to save changes in the draft?',

    save: 'Save',
    update_file_title: 'Update Your File Title',
    type_a_title: 'Type a Title',


    audioRecorder: "Audio Recorder",
    record: "Record",
    pause: "Pause",
    resume: "Resume",
    stop: "Stop",
    change_password: "Change Password",
    logout: "Logout",
    delete_account: "Delete Account",

    next: "NEXT",
    instructions: "Instructions",
    message: 'Message',
    instructions_read: "Please read all the instructions before clicking the next button",
    minute_left: 'minutes left',
    nextsmall: "Next",
    your_score: 'Your Score',
    you_have_successfully_completed_quiz: ' You have successfully completed Quiz.',
    need_help_for_solution_or_lost_something: 'Need help for solutions, or lost something!',
    feel_free_to_message_us: 'Feel free to message us.',
    email_address: 'example@gmail.com',
    your_data_is_uploded_sucessfully: 'Your homework is uploded sucessfully',
    error: 'Error',
    check_your_internet_connection: 'Please check your internet connection',
    something_went_wrong: "Oops, Something went wrong please try again after sometime",

    previous: "Previous"
}


